# Generated by Django 2.1.2 on 2018-10-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='remaining_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
